namespace: default

replicaCount: 2

image:
  repository: beltus325/hextris
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: hextris-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: hextris.rgfdevops.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - hextris.rgfdevops.cloud
      secretName: hextris-api-tls-secret

resources:
  requests:
    memory: "500Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
